#if !canImport(ObjectiveC)
import XCTest

extension GeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GeneratorTests = [
        ("testGenerator6DigitBase32SHA256", testGenerator6DigitBase32SHA256),
        ("testGenerator6DigitBase32SHA512", testGenerator6DigitBase32SHA512),
        ("testGenerator6DigitHexSHA1", testGenerator6DigitHexSHA1),
        ("testGenerator7DigitBase32SHA256", testGenerator7DigitBase32SHA256),
        ("testGenerator7DigitBase32SHA512", testGenerator7DigitBase32SHA512),
        ("testGenerator7DigitHexSHA1", testGenerator7DigitHexSHA1),
        ("testGenerator8DigitBase32SHA256", testGenerator8DigitBase32SHA256),
        ("testGenerator8DigitBase32SHA512", testGenerator8DigitBase32SHA512),
        ("testGenerator8DigitHexSHA1", testGenerator8DigitHexSHA1),
    ]
}

extension HOTPTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HOTPTests = [
        ("testHOTP", testHOTP),
    ]
}

extension TOTPTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TOTPTests = [
        ("test01", test01),
        ("test02", test02),
        ("test03", test03),
        ("test04", test04),
        ("test05", test05),
        ("test06", test06),
        ("test07", test07),
        ("test08", test08),
        ("test09", test09),
        ("test10", test10),
        ("test11", test11),
        ("test12", test12),
        ("test13", test13),
        ("test14", test14),
        ("test15", test15),
        ("test16", test16),
        ("test17", test17),
        ("test18", test18),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GeneratorTests.__allTests__GeneratorTests),
        testCase(HOTPTests.__allTests__HOTPTests),
        testCase(TOTPTests.__allTests__TOTPTests),
    ]
}
#endif
